name: Test CI

on: 
  push: 
    branches: 
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo push success
        run: echo "Push Success"
      
